In [15]:
import pandas as pd

In [17]:
Jobs = pd.read_csv("dataJobs/job_descriptions.csv")
Jobs.shape

(1615940, 23)

In [18]:
Jobs_shuffled = Jobs.sample(frac=1, random_state=42).reset_index(drop=True)

In [19]:
FinalJobs = Jobs_shuffled.iloc[:1000000]

In [20]:
#FinalJobs.to_csv("Jobs.csv" , index= False)
FinalJobs.columns, FinalJobs.shape

(Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
        'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
        'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
        'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
        'skills', 'Responsibilities', 'Company', 'Company Profile'],
       dtype='object'),
 (1000000, 23))

In [21]:
FinalJobs.sample(1)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
553702,2045807236091021,0 to 13 Years,BBA,$57K-$99K,Vientiane,Lao PDR,19.8563,102.4955,Full-Time,25694,...,2367759110,Electrical Designer,Electrical Engineer,USAJOBS,Electrical Engineers design and develop electr...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Electrical engineering Circuit design Electron...,Design electrical systems and components for b...,Skechers U.S.A.,"{""Sector"":""Consumer Discretionary"",""Industry"":..."

In [22]:
# 1. Create "workplace" column from "location" and "country"
FinalJobs["workplace"]= FinalJobs["location"]+" "+FinalJobs["Country"]
# 3. Create "working_mode" column from "Work Type"
FinalJobs["working_mode"] = FinalJobs["Work Type"]

# 4. Create "salary" column by calculating the average of Salary Range
def calculate_avg_salary(salary_range):
    if isinstance(salary_range, str) and "-" in salary_range:
        salary_range = salary_range.replace("$", "").replace("K", "").split("-")
        min_salary = float(salary_range[0]) * 1000
        max_salary = float(salary_range[1]) * 1000
        return (min_salary + max_salary) / 2
    return None

FinalJobs["salary"] = FinalJobs["Salary Range"].apply(calculate_avg_salary)

# 5. Create "position" column from "Job Title"
FinalJobs["position"] = FinalJobs["Job Title"]

# 6. Create "job_role_and_duties" from "Responsibilities", "Role", and "Job Description"
FinalJobs["job_role_and_duties"] = FinalJobs["Responsibilities"] +" " + FinalJobs["Role"] + FinalJobs["Job Description"]

# 7. Create "requisite_skill" from "skills", "Experience", and "Qualifications"
FinalJobs["requisite_skill"] = FinalJobs["skills"] + " " + FinalJobs["Experience"] +" "+ FinalJobs["Qualifications"]

# 8. Create "offer_details" from "Benefits"
FinalJobs["offer_details"] = FinalJobs["Benefits"]

# Drop unnecessary columns (optional)
FinalJobs = FinalJobs.drop(columns=["location", "Country", "latitude", "longitude", "Work Type", "Salary Range",
                                      "Job Title", "Responsibilities", "Role", "Job Description",
                                      "skills", "Experience", "Qualifications", "Benefits"])

C:\Users\ranas\AppData\Local\Temp\ipykernel_9340\857821168.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FinalJobs["workplace"]= FinalJobs["location"]+" "+FinalJobs["Country"]
C:\Users\ranas\AppData\Local\Temp\ipykernel_9340\857821168.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FinalJobs["working_mode"] = FinalJobs["Work Type"]
C:\Users\ranas\AppData\Local\Temp\ipykernel_9340\857821168.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FinalJobs["salary"] = FinalJobs["Salary Range"].apply(calculate_avg_salary)
C:\Users\ranas\AppData\Local\Temp\ipykernel_9340\857821168.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FinalJobs["position"] = FinalJobs["Job Title"]
C:\Users\ranas\AppData\Local\Temp\ipykernel_9340\857821168.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FinalJobs["job_role_and_duties"] = FinalJobs["Responsibilities"] +" " + FinalJobs["Role"] + FinalJobs["Job Description"]
C:\Users\ranas\AppData\Local\Temp\ipykernel_9340\857821168.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FinalJobs["requisite_skill"] = FinalJobs["skills"] + " " + FinalJobs["Experience"] +" "+ FinalJobs["Qualifications"]
C:\Users\ranas\AppData\Local\Temp\ipykernel_9340\857821168.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FinalJobs["offer_details"] = FinalJobs["Benefits"]

In [23]:
FinalJobs.columns

Index(['Job Id', 'Company Size', 'Job Posting Date', 'Preference',
       'Contact Person', 'Contact', 'Job Portal', 'Company', 'Company Profile',
       'workplace', 'working_mode', 'salary', 'position',
       'job_role_and_duties', 'requisite_skill', 'offer_details'],
      dtype='object')

In [24]:
FinalJobs = FinalJobs.drop(columns=['Company Size', 'Job Posting Date', 'Preference','Contact Person', 'Contact', 'Job Portal', 'Company', 'Company Profile'])

In [25]:
FinalJobs.columns

Index(['Job Id', 'workplace', 'working_mode', 'salary', 'position',
       'job_role_and_duties', 'requisite_skill', 'offer_details'],
      dtype='object')

In [26]:
FinalJobs.sample(1)

,Job Id,workplace,working_mode,salary,position,job_role_and_duties,requisite_skill,offer_details
869209,129308124259622,Marigot St. Martin (French part),Full-Time,83500.0,Registered Nurse,Supervise nursing staff and allocate patient a...,Nursing leadership Charge nurse responsibiliti...,"{'Flexible Spending Accounts (FSAs), Relocatio..."

In [27]:
for i in FinalJobs.columns:
  print( i , "is   ", FinalJobs[i][0])

Job Id is    1017340707950150
workplace is    Panama City Panama
working_mode is    Contract
salary is    69500.0
position is    Procurement Manager
job_role_and_duties is    Promote supplier diversity initiatives and inclusion. Identify and onboard diverse suppliers. Monitor compliance with diversity goals and regulations. Supplier Diversity ManagerPromote diversity and inclusion in the supply chain, manage supplier diversity programs, and assess supplier performance.
requisite_skill is    Supplier diversity programs Diversity and inclusion initiatives Supplier assessment and certification Data collection and reporting Vendor outreach and engagement Strategic planning Communication skills Relationship building Attention to diversity and inclusion principles 5 to 10 Years BBA
offer_details is    {'Transportation Benefits, Professional Development, Bonuses and Incentive Programs, Profit-Sharing, Employee Discounts'}

In [28]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download NLTK resources (if not already downloaded)
nltk.download('punkt')
nltk.download('stopwords')

ModuleNotFoundError: No module named 'nltk'

In [ ]:
import nltk
nltk.download('all')

In [ ]:
'''
Job Id is    1017340707950150
workplace is    Panama City Panama
working_mode is    Contract
salary is    69500.0
position is    Procurement Manager
job_role_and_duties is    Promote supplier diversity initiatives and inclusion. Identify and onboard diverse suppliers. Monitor compliance with diversity goals and regulations. Supplier Diversity ManagerPromote diversity and inclusion in the supply chain, manage supplier diversity programs, and assess supplier performance.
requisite_skill is    Supplier diversity programs Diversity and inclusion initiatives Supplier assessment and certification Data collection and reporting Vendor outreach and engagement Strategic planning Communication skills Relationship building Attention to diversity and inclusion principles 5 to 10 Years BBA
offer_details is    {'Transportation Benefits, Professional Development, Bonuses and Incentive Programs, Profit-Sharing, Employee Discounts'}
'''
# convert workplace to lowercase
FinalJobs["workplace"] = FinalJobs["workplace"].str.lower()
# convert working_mode to lowercase
FinalJobs["working_mode"] = FinalJobs["working_mode"].str.lower()
# convert position to lowercase
FinalJobs["position"] = FinalJobs["position"].str.lower()
# convert job_role_and_duties to lowercase and remove extra spaces
FinalJobs["job_role_and_duties"] = FinalJobs["job_role_and_duties"].str.lower().str.strip()
# convert requisite_skill to lowercase and remove extra spaces
FinalJobs["requisite_skill"] = FinalJobs["requisite_skill"].str.lower().str.strip()
# convert offer_details to lowercase and remove extra spaces and curly brackets
FinalJobs["offer_details"] = FinalJobs["offer_details"].str.lower().str.strip("{}")

In [ ]:
FinalJobs.sample(1)

In [ ]:
import re
# Remove special characters from "job_role_and_duties" and "requisite_skill" and offer_details
def remove_special_characters(text):
    return re.sub(r"[^a-zA-Z0-9 ]", "", text)

FinalJobs["job_role_and_duties"] = FinalJobs["job_role_and_duties"].apply(remove_special_characters)
FinalJobs["requisite_skill"] = FinalJobs["requisite_skill"].apply(remove_special_characters)
FinalJobs["offer_details"] = FinalJobs["offer_details"].apply(remove_special_characters)

In [ ]:
FinalJobs.sample(1)

In [ ]:
FinalJobs.to_csv("JobsFE.csv" , index= False)
FinalJobs.shape